//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.10 at 04:19:48 PM IST 
//


package com.packtpub.liverestaurant.orderservice.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FoodItemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FoodItemType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Snacks"/&gt;
 *     &lt;enumeration value="Beverages"/&gt;
 *     &lt;enumeration value="Starters"/&gt;
 *     &lt;enumeration value="Meals"/&gt;
 *     &lt;enumeration value="Coffee"/&gt;
 *     &lt;enumeration value="Juices"/&gt;
 *     &lt;enumeration value="Desserts"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FoodItemType")
@XmlEnum
public enum FoodItemType {

    @XmlEnumValue("Snacks")
    SNACKS("Snacks"),
    @XmlEnumValue("Beverages")
    BEVERAGES("Beverages"),
    @XmlEnumValue("Starters")
    STARTERS("Starters"),
    @XmlEnumValue("Meals")
    MEALS("Meals"),
    @XmlEnumValue("Coffee")
    COFFEE("Coffee"),
    @XmlEnumValue("Juices")
    JUICES("Juices"),
    @XmlEnumValue("Desserts")
    DESSERTS("Desserts");
    private final String value;

    FoodItemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FoodItemType fromValue(String v) {
        for (FoodItemType c: FoodItemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
